name: Sync Fork

on:
  schedule:
    - cron: '*/15 * * * *'

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Sync Fork with Upstream
        uses: TG908/fork-sync@v1.1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          owner: goyalaakarsh       
          base: main                
          head: main                
